name: emi_app
version: 1.0.0+1
publish_to: 'none'
description: A new Flutter project.

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: any
  get_cli: any
  google_fonts: any
  flutter_screenutil: any

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
